---
title: "Diamond"
author: "YJ"
date: "2023-05-28"
output: html_document
---


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(gcookbook)
library(tidyverse)
```

```{r}
setwd("C:/Users/user/Downloads")
Diamond= read.csv('Diamonds Prices2022.csv',header = T, encoding="UTF-8")
str(Diamond)
```

```{r}
Diamond$cut <-as.factor(Diamond$cut)
Diamond$cut<-factor(Diamond$cut, levels=c("Ideal", "Premium", "Very Good", "Good", "Fair" ))
Diamond$color<-as.factor(Diamond$color)
Diamond$color<-factor(Diamond$color, levels=c("D","E","F","G","H","I","J"))
Diamond$clarity<-as.factor(Diamond$clarity)
Diamond$clarity<-factor(Diamond$clarity, levels=c("IF","VVS1", "VVS2", "VS1","VS2","SI1","SI2","I1"))
Diamond$ratio <-Diamond$depth +Diamond$table
  
Diamond%>%
  mutate(ratio=case_when(Year<1970 ~"1960s",Year<1980 ~ "1970s",Year<1990 ~ "1980s",Year<2000 ~ "1990s",Year<2010 ~ "2000s",Year>=2010 ~ "2010s"))

ss$years <-as.factor(ss$years)
ss$years<-factor(ss$years, levels=c("1960s", "1970s","1980s","1990s","2000s","2010s"))

str(Diamond)
```
```{r}
df<-Diamond %>%
  group_by(cut)%>%
  summarise(price=mean(price))

```

```{r}
ggplot(Diamond, aes(x=cut, y=price, fill=cut, group=cut))+geom_col(stat = "identity") + labs(title="cut 등급별 가격 분포")+  coord_flip() #+scale_fill_brewer(palette = 'Pastel3')

ggplot(Diamond , aes(x=cut, y=price, fill=cut))+geom_boxplot()+ labs(title="cut 등급별 가격 분포") #+scale_fill_brewer(palette = 'Pastel3')
```
```{r}
asa <-Diamond %>%
  group_by(color)%>%
  summarise(price=mean(price))

ggplot(Diamond , aes(x=color, y=price, fill=color, color=color))+geom_col()+ labs(title="color 등급별 평균 가격")

ggplot(Diamond , aes(x=color, y=price, fill=color))+geom_boxplot()+ labs(title="color 등급별 가격 분포") #+scale_fill_brewer(palette = 'Pastel3')
```
```{r}
ass <-Diamond %>%
  group_by(clarity)%>%
  summarise(price=mean(price))

ggplot(Diamond  , aes(x=clarity, y=price, fill=clarity, color=clarity))+geom_col()+labs(title="clarity 등급별 평균 가격")

ggplot(Diamond , aes(x=clarity, y=price, fill=clarity))+geom_boxplot()+ labs(title="clarity 등급별 가격 분포")
```
```{r}
gg<- Diamond %>%
  group_by(clarity)

```
```{r}
ggplot(Diamond  , aes(x=clarity, y=carat, fill=clarity))+geom_col()
ggplot(Diamond , aes(x=clarity, y=carat, fill=clarity))+geom_point()+ labs(title="clarity 등급별 가격 분포")
```
```{r}
df1<-Diamond%>%
  group_by(cut)

ggplot(Diamond , aes(x=cut, y=carat, fill=cut))+geom_col()
ggplot(Diamond , aes(x=cut, y=carat, fill=cut))+geom_boxplot()+ labs(title="clarity 등급별 가격 분포")
```
```{r}
df2<-Diamond%>%
  group_by(color)

ggplot(Diamond , aes(x=color, y=carat, fill=color))+geom_col()
ggplot(Diamond , aes(x=color, y=carat, fill=color))+geom_boxplot()+ labs(title="clarity 등급별 가격 분포")
```

```{r}
ggplot(Diamond , aes(x=carat, y=log_price))+geom_point(size=1.5)
```
```{r}
ggplot(Diamond , aes(x=x, y=log_price))+geom_point(size=1.5)
```
```{r}
ggplot(Diamond , aes(x=y, y=log_price))+geom_point(size=1.5)
```
```{r}
ggplot(Diamond , aes(x=z, y=log_price))+geom_point(size=1.5)
```


